#!/usr/bin/env python3

import sys

SUCCESS = 0
ERROR = 84


def print_help(output=sys.stdout) -> None:
    print(
        """USAGE
\t./107transfer [num den]+

DESCRIPTION
\tnum\tpolynomial numerator defined by its coefficients
\tden\tpolynomial denominator defined by its coefficients
""",
        file=output,
    )


def horner(polynome, x):
    result = polynome[0]

    for i in range(1, len(polynome)):
        result = result * x + polynome[i]

    return result


def main() -> None:
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print_help()
        sys.exit(SUCCESS)

    if len(sys.argv) == 1 or len(sys.argv) % 2 != 1:
        print("Incorrect number of arguments", file=sys.stderr)
        print_help(sys.stderr)
        sys.exit(ERROR)

    for i in range(1, len(sys.argv)):
        try:
            tmp_str = sys.argv[i].split("*")
            tmp = [float(x) for x in tmp_str]
        except ValueError:
            print("Error: not a number", file=sys.stderr)
            sys.exit(ERROR)

    for i in range(1001):
        result = 1
        for j in range(1, len(sys.argv), 2):
            numerator_str = sys.argv[j].split("*")
            numerator_str.reverse()
            numerator = [float(x) for x in numerator_str]
            numerator_result = horner(numerator, i / 1000)
            denominator_str = sys.argv[j + 1].split("*")
            denominator_str.reverse()
            denominator = [float(x) for x in denominator_str]
            denominator_result = horner(denominator, i / 1000)
            if denominator_result == 0:
                print("not divisible by zero", file=sys.stderr)
                sys.exit(ERROR)
            result *= numerator_result / denominator_result
        print(f"{i / 1000:.3f} -> {result:.5f}")

    sys.exit(SUCCESS)


if __name__ == "__main__":
    main()
