#!/usr/bin/env python3
import sys
import math


def check_args():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print("USAGE\n    ./103cipher message key flag\n")
        print("DESCRIPTION")
        print("    message     a message, made of ASCII characters")
        print("    key         the encryption key, made of ASCII characters")
        print("    flag        0 for the message to be encrypted, 1 to be decrypted")
        sys.exit(0)
    
    if len(sys.argv) != 4:
        print("Error: wrong number of arguments", file=sys.stderr)
        sys.exit(84)
    
    message = sys.argv[1]
    key = sys.argv[2]
    
    try:
        flag = int(sys.argv[3])
        if flag not in [0, 1]:
            raise ValueError
    except:
        print("Error: flag must be 0 or 1", file=sys.stderr)
        sys.exit(84)
    
    return message, key, flag


def key_to_matrix(key):
    ascii_key = [ord(c) for c in key]
    size = math.ceil(math.sqrt(len(ascii_key)))
    
    while len(ascii_key) < size * size:
        ascii_key.append(0)
    
    matrix = []
    for i in range(size):
        row = []
        for j in range(size):
            row.append(ascii_key[i * size + j])
        matrix.append(row)
    
    return matrix


def print_key_matrix(matrix):
    print("Key matrix:")
    for row in matrix:
        print('\t'.join(map(str, row)))


def message_to_matrix(message, key_size):
    ascii_msg = [ord(c) for c in message]
    
    while len(ascii_msg) % key_size != 0:
        ascii_msg.append(0)
    
    matrix = []
    for i in range(0, len(ascii_msg), key_size):
        row = ascii_msg[i:i + key_size]
        matrix.append(row)
    
    return matrix


def multiply_matrices(msg_matrix, key_matrix):
    result = []
    
    for row in msg_matrix:
        new_row = []
        for col_idx in range(len(key_matrix)):
            sum_val = 0
            for k in range(len(row)):
                sum_val += row[k] * key_matrix[k][col_idx]
            new_row.append(sum_val)
        result.append(new_row)
    
    return result


def encrypt(message, key):
    key_matrix = key_to_matrix(key)
    print_key_matrix(key_matrix)
    
    msg_matrix = message_to_matrix(message, len(key_matrix))
    
    encrypted_matrix = multiply_matrices(msg_matrix, key_matrix)
    
    print("Encrypted message:")
    encrypted_numbers = []
    for row in encrypted_matrix:
        encrypted_numbers.extend(row)
    print(' '.join(map(str, encrypted_numbers)))


def main():
    message, key, flag = check_args()
    
    if flag == 0:
        encrypt(message, key)

if __name__ == "__main__":
    main()
